07/17/2024 10:21:58 PM: INFO: ******** Started : test_verify_title_page ********
07/17/2024 10:21:59 PM: ERROR: ******** Exception occurred in test_verify_title_page ********
Traceback (most recent call last):
  File "/Users/sdahal/GitRepos/PythonProgrammingBatch2024/CorePython/FrameworkDesign/testCases/test_login.py", line 26, in test_verify_title_page
    assert actual_title == 'Account Logdxina', "Title is not as expected!"
AssertionError: Title is not as expected!
assert 'Account Login' == 'Account Logdxina'
  
  - Account Logdxina
  ?            --  -
  + Account Login
07/17/2024 10:21:59 PM: INFO: ******** Started : test_verify_login_elements_displayed ********
07/17/2024 10:21:59 PM: INFO: ******** Finished : test_verify_login_elements_displayed (PASSED) ********
07/17/2024 10:22:00 PM: INFO: ******** Started : test_verify_login_elements_text ********
07/17/2024 10:22:00 PM: INFO: ******** Finished : test_verify_login_elements_text (PASSED) ********
07/17/2024 10:22:00 PM: INFO: ******** Started : test_verify_login_with_invalid_credentials ********
07/17/2024 10:22:03 PM: ERROR: ******** Exception occurred in test_verify_login_with_invalid_credentials ********
Traceback (most recent call last):
  File "/Users/sdahal/GitRepos/PythonProgrammingBatch2024/CorePython/FrameworkDesign/testCases/test_login.py", line 68, in test_verify_login_with_invalid_credentials
    assert self.login_page.get_alert_warning_both_no_match() == exp_warning_msg, "Warning message not as expected for invalid credentials."
AssertionError: Warning message not as expected for invalid credentials.
assert 'Warning: You...in in 1 hour.' == 'Warning: No .../or Password.'
  
  - Warning: No match for E-Mail Address and/or Password.
  + Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.
